language: python
sudo: false
python:
  - "3.6"
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"
  - "2.6"
  - "pypy"
  - "pypy3"
env:
  - LC_ALL="en_US.utf-8"
  - LC_ALL="en_US.ascii"
matrix:
  allow_failures:
  # pypy3 segfaults for some reason
  - python: "pypy3"
branches:
  only:
    - develop
install:
  - "python -c \"import sys; print(sys.getfilesystemencoding())\""
  - "pip install --upgrade setuptools"
  - "pip install --upgrade pytest"
  - "pip install pytest-cov"
  - "pip install -r requirements.txt"
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then pip install check-manifest flake8; fi"
  - "pip install ."
script:
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then check-manifest; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then flake8; fi"
  - cd tests
  - "pytest test_pathlib2.py --cov=pathlib2"
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then python test_pathlib2_with_py2_unicode_literals.py; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then python test_pathlib2_with_py2_unicode_literals.py; fi"
after_success:
  - bash <(curl -s https://codecov.io/bash)
