language: python
sudo: false
python:
  - "3.6"
  - "3.5"
  - "3.4"
  - "3.3"
  - "3.2"
  - "2.7"
  - "2.6"
  - "pypy"
  - "pypy3"
branches:
  only:
    - develop
install:
  - "pip install -r requirements.txt"
  - "if [[ $TRAVIS_PYTHON_VERSION != '3.2' ]]; then pip install pytest-cov; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.2' ]]; then pip install pytest; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then pip install check-manifest flake8; fi"
script:
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then check-manifest; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then flake8; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION != '3.2' ]]; then py.test test_pathlib2.py --cov=pathlib2; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.2' ]]; then py.test test_pathlib2.py; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then python -Qnew test_pathlib2.py; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then python test_pathlib2_with_py2_unicode_literals.py; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then python -Qnew test_pathlib2.py; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then python test_pathlib2_with_py2_unicode_literals.py; fi"
after_success:
  - bash <(curl -s https://codecov.io/bash)
