environment:

  matrix:
    - PYTHON: "C:\\Python26"

    - PYTHON: "C:\\Python27"

    - PYTHON: "C:\\Python33"

    - PYTHON: "C:\\Python34"

    - PYTHON: "C:\\Python35"

    - PYTHON: "C:\\Python36"

init:
  - "%PYTHON%/python --version"

install:
  - "powershell appveyor\\install.ps1"

build: off

test_script:
  - "%PYTHON%/Scripts/py.test test_pathlib2.py --cov=pathlib2"

after_test:
  - "SET PATH=%PYTHON%/Scripts;%PATH%"
  - "codecov"

